### ISSUE TITLE
Plan to update to terraform 0.9?

### ISSUE THREAD

**Issue by geertbrit** [elricsfate/terraform-provider-vultr#7]
Might be stretching it, but do you plan to support terraform 0.9 eventually?

**Comment by rolele** [comment]
I would very much like that because I can not build the 0.8.8 version of terraform locally.
So basically I can not use the vultr plugin.

**Comment by rtizzy** [comment]
@gebrits @rolele 

That's something I'll investigate in the near future, been working on some other stuff. 

in there interim would a compiled version for 0.8.8 help you guys out? 

The build instructions should work and were tested just recently.

**Comment by rtizzy** [comment]
@gebrits @rolele 

The latest version of Terraform is now supported and a release has been uploaded. 
Let me know if you continue to have issues. 

ad823b2b24c87e3ee303c00831a880b2afe5f443

Closing issue.
